### ISSUE TITLE
Examples wanted

### ISSUE THREAD

**Issue by jacmoe** [frank256/lgui#3]
I am currently overwhelmed by browsing through the many, many files in the `tests` directory.

A couple of simple examples of how to integrate this with your existing projects would be really nice!

I notice that it uses some Allegro transforms, so that probably has to be set for the GUI. I am not using transform in my project because I draw pixels only.

I am sure that I can manage to figure it out, but I am sure that people will appreciate if there are a couple of "getting started" examples for this library :)

**Comment by jacmoe** [comment]
I just generated the docs, and the documentation there is excellent; kudos! 💯 

Maybe I will convert the main parts into markdown for those of us who don't generate the docs unless we have to.

That would probably stop people like me from creating pointless Github issues asking for features that are already there ;p

**Comment by jacmoe** [comment]
I tell you what, I will just add a minimal, self-contained example. Expect another PR shortly.

I have to say that the documentation is excellent!

**Comment by frank256** [comment]
Thank you for the feedback and PRs, much appreciated!
I thought about auto-generating the docs and hosting them online somewhere (GitHub?) but I've never done that before. Yes, the readme.md could probably be expanded with a bit more hands-on info. As said on allegro.cc, I'm a bit busy this week...

Edit: About the Allegro transforms lgui uses, you do not really need to care about them. If you do not use any of lgui's transform capabilities (which are mostly intended for transition effects), they are purely used for translating stuff when changing the current drawing rect (so each widget can draw to its own origin). They should be reset when lgui's drawing is done. So yes, it's basically "pixels only", too.

**Comment by frank256** [comment]
Finally managed to add two basic examples:
See https://github.com/frank256/lgui/tree/develop/src/example
